name:                threepenny-editors
version:             0.2.0.4
synopsis:            Composable algebraic editors
description:         Please see Readme.md
homepage:            https://github.com/pepeiborra/threepenny-editors
license:             BSD3
author:              Jose Iborra
maintainer:          pepeiborra@gmail.com
copyright:           All Rights Reserved
category:            Web
extra-source-files:
- README.md
ghc-options: -Wall -Wno-name-shadowing
description: |
    This package provides a type class 'Editable' and combinators to
    easily put together form-like editors for algebraic datatypes.
    .
    NOTE: This library contains examples, but they are not built by default.
    To build and install the example, use the @buildExamples@ flag like this
    .
    @cabal install threepenny-editors -fbuildExamples@

flags:
  buildExamples:
    description: build the examples
    default: False
    manual : True

library:
  source-dirs: 	src
  exposed-modules:
    - Graphics.UI.Threepenny.Editors
    - Graphics.UI.Threepenny.Editors.Base
    - Graphics.UI.Threepenny.Editors.Profunctor
  dependencies:
    - base >= 4.7 && < 5
    - profunctors
    - threepenny-gui > 0.7

executables:
  person:
    source-dirs:  examples
    main: Person.hs
    when:
      condition: flag(buildExamples)
      then:
        dependencies:
          - base
          - profunctors
          - threepenny-gui
          - threepenny-editors
      else: 
        buildable: False
